import { StatIdType } from "@/types/IdTypes/StatIdTypes";

export type StatInfo = {
  name: string;
  category?: "offense" | "defense" | "movement" | "general";
};

export const getStatName = (statId: StatIdType): StatInfo => {
  const statMap: Record<StatIdType, StatInfo> = {
    "1": { name: "Unknown Stat 1", category: "general" },
    "2": { name: "Unknown Stat 2", category: "general" },
    "3": { name: "Unknown Stat 3", category: "general" },
    "4": { name: "Unknown Stat 4", category: "general" },
    "5": { name: "Unknown Stat 5", category: "general" },
    "6": { name: "Unknown Stat 6", category: "general" },
    "7": { name: "Unknown Stat 7", category: "general" },
    "8": { name: "Unknown Stat 8", category: "general" },
    "9": { name: "Unknown Stat 9", category: "general" },
    "10": { name: "Unknown Stat 10", category: "general" },
    "11": { name: "Unknown Stat 11", category: "general" },
    "12": { name: "Unknown Stat 12", category: "general" },
    "13": { name: "Unknown Stat 13", category: "general" },
    "14": { name: "Unknown Stat 14", category: "general" },
    "15": { name: "Unknown Stat 15", category: "general" },
    "16": { name: "Unknown Stat 16", category: "general" },
    "17": { name: "Unknown Stat 17", category: "general" },
    "18": { name: "Touchdowns Scored", category: "offense" },
    "19": { name: "Casualties Inflicted", category: "offense" },
    "20": { name: "Unknown Stat 20", category: "general" },
    "21": { name: "Deaths Inflicted", category: "offense" },
    "22": { name: "Injuries Inflicted", category: "offense" },
    "23": { name: "Yards Running With Ball", category: "movement" },
    "24": { name: "Unknown Stat 24", category: "general" },
    "25": { name: "KOs Inflicted", category: "offense" },
    "26": { name: "Block Actions Made", category: "offense" },
    "27": { name: "Touchdowns Against", category: "defense" },
    "28": { name: "Casualties Sustained", category: "defense" },
    "29": { name: "Unknown Stat 29", category: "general" },
    "30": { name: "Injuries Sustained", category: "defense" },
    "31": { name: "Deaths Sustained", category: "defense" },
    "32": { name: "Unknown Stat 32", category: "general" },
    "33": { name: "Unknown Stat 33", category: "general" },
    "34": { name: "Unknown Stat 34", category: "general" },
    "35": { name: "Unknown Stat 35", category: "general" },
    "36": { name: "Unknown Stat 36", category: "general" },
    "37": { name: "Unknown Stat 37", category: "general" },
    "38": { name: "Unknown Stat 38", category: "general" },
    "39": { name: "Unknown Stat 39", category: "general" },
    "40": { name: "Unknown Stat 40", category: "general" },
    "41": { name: "Unknown Stat 41", category: "general" },
    "42": { name: "Yards Rushing (GFI)", category: "movement" },
    "43": { name: "Dodge Attempts", category: "movement" },
    "44": { name: "Dodge Successes", category: "movement" },
    "45": { name: "Rush Attempts", category: "movement" },
    "46": { name: "Rush Successes", category: "movement" },
    "47": { name: "Unknown Stat 47", category: "general" },
    "48": { name: "Unknown Stat 48", category: "general" },
    "49": { name: "Blitz Actions Made", category: "offense" },
    "50": { name: "Unknown Stat 50", category: "general" },
    "51": { name: "Unknown Stat 51", category: "general" },
    "52": { name: "Unknown Stat 52", category: "general" },
    "53": { name: "Unknown Stat 53", category: "general" },
    "54": { name: "Unknown Stat 54", category: "general" },
    "55": { name: "Unknown Stat 55", category: "general" },
    "56": { name: "Unknown Stat 56", category: "general" },
    "57": { name: "Unknown Stat 57", category: "general" },
    "58": { name: "Unknown Stat 58", category: "general" },
    "59": { name: "Blocks Sustained", category: "defense" },
    "60": { name: "Unknown Stat 60", category: "general" },
    "61": { name: "Armor Breaks (Offense)", category: "offense" },
    "62": { name: "Unknown Stat 62", category: "general" },
    "63": { name: "Unknown Stat 63", category: "general" },
    "64": { name: "Unknown Stat 64", category: "general" },
    "65": { name: "Unknown Stat 65", category: "general" },
    "66": { name: "Unknown Stat 66", category: "general" },
    "67": { name: "Unknown Stat 67", category: "general" },
    "68": { name: "Unknown Stat 68", category: "general" },
    "69": { name: "Unknown Stat 69", category: "general" },
    "70": { name: "Unknown Stat 70", category: "general" },
    "71": { name: "Unknown Stat 71", category: "general" },
    "72": { name: "Unknown Stat 72", category: "general" },
    "73": { name: "Unknown Stat 73", category: "general" },
    "74": { name: "Unknown Stat 74", category: "general" },
    "75": { name: "Unknown Stat 75", category: "general" },
    "76": { name: "Turns Played", category: "general" },
    "77": { name: "Unknown Stat 77", category: "general" },
    "78": { name: "Unknown Stat 78", category: "general" },
    "79": { name: "Unknown Stat 79", category: "general" },
    "80": { name: "Unknown Stat 80", category: "general" },
    "81": { name: "Unknown Stat 81", category: "general" },
    "82": { name: "Unknown Stat 82", category: "general" },
    "83": { name: "Unknown Stat 83", category: "general" },
    "84": { name: "Unknown Stat 84", category: "general" },
    "85": { name: "Unknown Stat 85", category: "general" },
    "86": { name: "Unknown Stat 86", category: "general" },
    "87": { name: "Unknown Stat 87", category: "general" },
    "88": { name: "Unknown Stat 88", category: "general" },
    "89": { name: "Unknown Stat 89", category: "general" },
    "90": { name: "Unknown Stat 90", category: "general" },
    "91": { name: "Unknown Stat 91", category: "general" },
    "92": { name: "Unknown Stat 92", category: "general" },
    "93": { name: "Unknown Stat 93", category: "general" },
    "94": { name: "Unknown Stat 94", category: "general" },
    "95": { name: "Unknown Stat 95", category: "general" },
    "96": { name: "Unknown Stat 96", category: "general" },
    "97": { name: "Unknown Stat 97", category: "general" },
    "98": { name: "Unknown Stat 98", category: "general" },
    "99": { name: "Unknown Stat 99", category: "general" },
    "100": { name: "Unknown Stat 100", category: "general" },
    "1070": { name: "Unknown Stat 1070", category: "general" },
    "1071": { name: "Unknown Stat 1071", category: "general" },
    passes_attempted: { name: "Passes Attempted", category: "offense" },
    passes_completed: { name: "Passes Completed", category: "offense" },
  };

  return (
    statMap[statId] || { name: `Unknown Stat ${statId}`, category: "general" }
  );
};
